# ui
library("shiny")
library("wordcloud2")
library("rhandsontable")

ui = fluidPage(titlePanel("Wordcloud2"),
               tags$hr(),
               fluidRow(div(width = "100%",
                            style = "background-color: #CDE9FA; margin: 0px; padding: 10px; padding-top: 1px; padding-bottom: 20px;",
                            h3("잠깐!"),
                            HTML(" 업로드 하는 파일은 header가 있는 csv 파일을 사용해주세요."),
                            br(),
                            HTML(" 첫 번째 column은 단어, 두 번째 column은 빈도가 들어가야 합니다."))),
               tags$hr(),
               br(),
               sidebarLayout(sidebarPanel(fileInput(inputId = "file",
                                                    label   = "Upload CSV File",
                                                    accept  = c("text/csv", 
                                                                "text/comma-separated-values",
                                                                "text/plain", 
                                                                ".csv")),
                                          sliderInput(inputId = "slider_rotate",
                                                      label = "Rotate Ratio",
                                                      min = 0,
                                                      max = 1,
                                                      step = 0.05,
                                                      value = 0.5),
                                          sliderInput(inputId = "slider_rotate_min",
                                                      label = "Rotate Min(degree)",
                                                      min = 0,
                                                      max = 360,
                                                      step = 1,
                                                      value = 90),
                                          sliderInput(inputId = "slider_rotate_max",
                                                      label = "Rotate Max(degree)",
                                                      min = 0,
                                                      max = 360,
                                                      step = 1,
                                                      value = 90),
                                          sliderInput(inputId = "slider_text_min",
                                                      label = "Minimum Text size",
                                                      min = 0,
                                                      max = 50,
                                                      step = 1,
                                                      value = 10),
                                          actionButton(inputId = "summit",
                                                       label = "Summit", 
                                                       width = "100%",
                                                       style = "background-color: #276596; color: #FFFFFF; font-size: 150%;")),
                             mainPanel(wordcloud2Output(outputId = "wordcloud",
                                                        height = "500px",
                                                        width  = "500px"),
                                       br(),
                                       rHandsontableOutput(outputId = "table",
                                                           width = "100%"))))
